name: CD on Main Branch Push

on:
  push:
    branches:
      - main

jobs:
  delivery:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: ソースコードのダウンロード
        uses: actions/checkout@v7

      - name: Node.js のセットアップ
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: 依存関係のインストール
        run: npm ci

      - name: アプリケーションのビルド
        run: npm run build

      - name: GitHub Packages へのログイン
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Short Commit Hash の設定
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> "${GITHUB_ENV}"

      - name: Docker Image のビルド
        run: docker build -t ghcr.io/${{ github.repository }}:${{ env.SHORT_SHA }} .

      - name: Docker Image のアップロード
        run: docker push ghcr.io/${{ github.repository }}:${{ env.SHORT_SHA }}
