name: CI on Pull Request

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  integration:
    runs-on: ubuntu-latest

    steps:
      - name: ソースコードのダウンロード
        uses: actions/checkout@v7

      - name: Node.js のセットアップ
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: 依存関係のインストール
        run: npm ci

      - name: ビルドが成功するか？
        run: npm run build

      - name: テストが成功するか？
        run: npm run test
